Quiz Pages and Fixed Greetings UI
jcmbaylen/molang-web-app pull request #3
Opened 2023-04-09 07:46 UTC by jcmbaylen

-Quiz Pages 
-Quiz Button
-Greetings Button

2023-04-09 09:16 UTC, jreybaylen commented on src/scss/learnings.module.scss
> +            // }
Remove the code if it is no longer needed

2023-04-09 09:16 UTC, jreybaylen commented on src/scss/letter.module.scss
> +        height: 300px;
Avoid using image static measurement

2023-04-09 09:17 UTC, jreybaylen commented on src/scss/greetings.module.scss
> +        // padding-bottom: 100px;
Remove the code if it is no longer needed

2023-04-09 09:17 UTC, jreybaylen commented on src/scss/greetings.module.scss
> +        background-color: aqua;
Move the color to `colors.scss`

2023-04-09 09:18 UTC, jreybaylen commented on src/scss/greetings.module.scss
> +    margin-top: 20vh;
Avoid using `vh` when it comes to margin, it may lead to wrong measurement

2023-04-09 09:18 UTC, jreybaylen commented on src/scss/greetings.module.scss
> +                height: 200px;
Avoid image static measurement

2023-04-09 09:18 UTC, jreybaylen commented on src/scss/greetings.module.scss
> +            .image {
Add spacing

2023-04-09 09:19 UTC, jreybaylen commented on src/scss/alphabet.module.scss
> +        h1:hover {
This should be in the h1 `&:hover`

2023-04-09 09:19 UTC, jreybaylen commented on src/scss/alphabet.module.scss
> +    // }
Remove the code if it is no longer needed

2023-04-09 09:21 UTC, jreybaylen commented on src/scss/alphabet.module.scss
> +    .alphabetQuiz {
Apply the kebab naming convention when it comes to CSS here. Check this [link](https://www.freecodecamp.org/news/programming-naming-conventions-explained/#:~:text=What%20is%20Kebab%20Case%3F,%2Dname%20and%20last%2Dname%20.)

2023-04-09 09:22 UTC, jreybaylen commented on src/scss/alphabet.module.scss
> +    // }
Remove the code if it is no longer needed

2023-04-09 09:22 UTC, jreybaylen commented on src/scss/alphabet.module.scss
> +    margin-top: 15vh;
Feedback would be the same as [here](https://github.com/jcmbaylen/molang-web-app/pull/3/files#r1161253403)

2023-04-09 09:22 UTC, jreybaylen commented on src/scss/alphabet-quiz.module.scss
> +            h2 {
Remove spacing

2023-04-09 09:23 UTC, jreybaylen commented on src/scss/alphabet-quiz.module.scss
> +    margin-top: 10vh;
Feedback would be the same as [here](https://github.com/jcmbaylen/molang-web-app/pull/3/files#r1161253403)

2023-04-09 09:23 UTC, jreybaylen commented on src/pages/learnings/alphabet/quiz.tsx
> +/* eslint-disable react/no-unescaped-entities */
Remove this. Fix the typescript issue with proper types

2023-04-09 09:24 UTC, jreybaylen commented on src/pages/learnings/alphabet/index.tsx
> +            </main> */}
Remove unused code here

2023-04-09 09:24 UTC, jreybaylen requested changes
Kindly check the following change requests

2023-04-10 01:11 UTC, jcmbaylen commented on src/scss/learnings.module.scss
> +            // }
Done

2023-04-10 01:12 UTC, jcmbaylen commented on src/scss/letter.module.scss
> +        height: 300px;
Done

2023-04-10 01:13 UTC, jcmbaylen commented on src/scss/greetings.module.scss
> +        // padding-bottom: 100px;
Done

2023-04-10 01:16 UTC, jcmbaylen commented on src/scss/greetings.module.scss
> +        background-color: aqua;
Done, I remove it. I forgot to remove it.

2023-04-10 01:17 UTC, jcmbaylen commented on src/scss/greetings.module.scss
> +    margin-top: 20vh;
Done I change it to percentage

2023-04-10 01:36 UTC, jcmbaylen commented on src/scss/greetings.module.scss
> +                height: 200px;
Done

2023-04-10 01:37 UTC, jcmbaylen commented on src/scss/greetings.module.scss
> +            .image {
Done

2023-04-10 01:38 UTC, jcmbaylen commented on src/scss/alphabet.module.scss
> +        h1:hover {
Done

2023-04-10 01:41 UTC, jcmbaylen commented on src/scss/alphabet.module.scss
> +    .alphabetQuiz {
Done

2023-04-10 01:41 UTC, jcmbaylen commented on src/scss/alphabet.module.scss
> +    // }
Done

2023-04-10 01:53 UTC, jcmbaylen commented on src/scss/alphabet-quiz.module.scss
> +            h2 {
Done

2023-04-10 01:53 UTC, jcmbaylen commented on src/scss/alphabet-quiz.module.scss
> +    margin-top: 10vh;
Done

2023-04-10 01:54 UTC, jcmbaylen commented on src/pages/learnings/alphabet/index.tsx
> +            </main> */}
Done

2023-04-10 02:04 UTC, jcmbaylen commented on src/pages/learnings/alphabet/quiz.tsx
> +/* eslint-disable react/no-unescaped-entities */
Done

2023-04-10 04:20 UTC, jreybaylen commented on src/pages/learnings/alphabet/quiz.tsx
> +                <h1>What hand gesture is letter {'"Letter"'}?</h1>
I suggest to use this [HTML Entity](https://www.w3schools.com/html/html_entities.asp) instead of this pattern you made

2023-04-10 04:21 UTC, jreybaylen commented on src/scss/alphabet.module.scss
> +    @media screen and (max-width: 560px) {
Add spacing

2023-04-10 04:21 UTC, jreybaylen commented on src/scss/alphabet.module.scss
> +            a {
Add spacing

2023-04-10 04:21 UTC, jreybaylen commented on src/scss/greetings.module.scss
> +            .icon {
Ad spacing

2023-04-10 04:21 UTC, jreybaylen commented on src/scss/greetings.module.scss
>          .button:hover {
Add spacing

2023-04-10 04:21 UTC, jreybaylen commented on src/scss/greetings.module.scss
>      @media screen and (max-width: 768px) {
Add spacing

2023-04-10 04:22 UTC, jreybaylen commented on src/scss/greetings.module.scss
> +                .icon {
Add spacing

2023-04-10 04:22 UTC, jreybaylen commented on src/scss/learnings.module.scss
> +                img {
Add spacing

2023-04-10 04:22 UTC, jreybaylen commented on src/scss/letter.module.scss
>  }
Remove spacing

2023-04-10 04:22 UTC, jreybaylen requested changes
Kindly check the change requests. Make sure you apply it to all.

2023-04-10 04:24 UTC, jreybaylen commented
Commit messages should be related to your changes and make sure it explains all the changes you applied

2023-04-10 06:44 UTC, jcmbaylen commented on src/scss/greetings.module.scss
> +            .icon {
Done

2023-04-10 06:46 UTC, jcmbaylen commented on src/scss/greetings.module.scss
>          .button:hover {
Done

2023-04-10 06:46 UTC, jcmbaylen commented on src/scss/greetings.module.scss
>      @media screen and (max-width: 768px) {
Done

2023-04-10 06:46 UTC, jcmbaylen commented on src/scss/greetings.module.scss
> +                .icon {
Doe

2023-04-10 06:47 UTC, jcmbaylen commented on src/scss/learnings.module.scss
> +                img {
Done

2023-04-10 06:48 UTC, jcmbaylen commented on src/scss/letter.module.scss
>  }
Done

2023-04-10 08:24 UTC, jreybaylen approved these changes

2023-04-10 08:24 UTC, merged